// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0xq1bV0XcmR8kmZCrG6ZZr-SyfCtfGrs',
    appId: '1:296618411663:web:d19adea0177098c79a92fa',
    messagingSenderId: '296618411663',
    projectId: 'js-champion-7c9f9',
    authDomain: 'js-champion-7c9f9.firebaseapp.com',
    storageBucket: 'js-champion-7c9f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8z8hjUx5CC25zFUa4eruPWwjZztLMxRU',
    appId: '1:296618411663:android:6aa564146782c1ca9a92fa',
    messagingSenderId: '296618411663',
    projectId: 'js-champion-7c9f9',
    storageBucket: 'js-champion-7c9f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQigMVddHHoEIPCsBG7Kl2rpdRNes3QzA',
    appId: '1:296618411663:ios:7338cb916dab12dc9a92fa',
    messagingSenderId: '296618411663',
    projectId: 'js-champion-7c9f9',
    storageBucket: 'js-champion-7c9f9.appspot.com',
    iosClientId: '296618411663-45j84ccu6big6t43fk899fptvkbd1msp.apps.googleusercontent.com',
    iosBundleId: 'com.example.jsChampion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQigMVddHHoEIPCsBG7Kl2rpdRNes3QzA',
    appId: '1:296618411663:ios:7338cb916dab12dc9a92fa',
    messagingSenderId: '296618411663',
    projectId: 'js-champion-7c9f9',
    storageBucket: 'js-champion-7c9f9.appspot.com',
    iosClientId: '296618411663-45j84ccu6big6t43fk899fptvkbd1msp.apps.googleusercontent.com',
    iosBundleId: 'com.example.jsChampion',
  );
}
